### ISSUE TITLE
I dont see Boilerplates

### ISSUE THREAD

**Issue by schroef** [Hennamann/CEP-Toolkit#1]
Hi there,

i just found your repo today and was wondering where the Boilerplates are? I don't see anything of that in this repo? I only see UI templates

**Comment by Hennamann** [comment]
I had several boilerplates planned, and i actually made one for spectrum which had it's own repo which i believe was submoduled into this repo aswell(or just copied over) unfortunatley it was taken down by Adobe despite the code in use from Adobe being open source and under a permissive reuse lisence. 

I'll remove the mention of boilerplates from the code to avoid future confusion. 

(P.s my CEP extension creator for vscode repo still has the spectrum boilerplate along with a few other boilerplates.)

**Comment by schroef** [comment]
Thanks for the fast reply!!! Much appreciated :)

Im very new to making panels as I'm upgrading the AnimDessin2 panel. Very cool tool! I have already added some big improvements now. I was looking into the meaning of these boilerplates and how they can be used.

I don't know much about that Spectrum yet. So far as i can tell its a template, so its styles the panel. Very clean i believe.

But yeah, that's a crappy move by Adobe. Did they make any comment on why they took it down? Ill have a look at that extension creator. Thanks for the advice!

**Comment by schroef** [comment]
PS weird they took this one down but your Extention Creator still has it??? Prhaps I'm not understanding it correct.

Doesnt Davide Barranca also use it in his templates? That man seems like a panel god!! But i find that book he has a bit pricy at the moment. But i do think about getting it eventually

**Comment by Hennamann** [comment]
Here's the full DMCA request: https://github.com/github/dmca/blob/master/2018/2018-01-04-Adobe.md 

I'm obviously not a lawyer and i never bothered to reach out to them over such a silly issue, but i do feel they handled it badly. The source code i put in the repo was found in a public repository by Adobe with a permissive license allowing reuse, redistribution etc: https://github.com/adobe-photoshop/generator-panels. The one thing i did that i can somewhat understand their frustration with was the fact that some of my wording in the repo may have come off as if Adobe had sanctioned the project and that it came from them. Which it did not. But they could have just told me to change that over an e-mail, instead they just went full lawyer which just leaves a bad taste to be honest.

Alright, that's that tangen out of the way. I don't think Adobe minds people using the spectrum CSS files for extensions or projects, it boiled down to the way i was portraying it in that repo.  Which is why both me and Davide barranca still use those CSS files, heck i've even discussed this with Adobe employees who say it's a non-issue.
